### ISSUE TITLE
Uncaught Error: Class 'kolabformat' not found

### ISSUE THREAD

**Issue by Yannik** [texxasrulez/caldav_calendar#20]
Hi, when I'm trying to open the calendar config page in settings, I get the following error:
```
[30-Apr-2020 22:45:59 +0200]: <pj1luo6q> PHP Error: required kolabformat module not found (POST /webmail/?_task=settings&_action=refresh)
[30-Apr-2020 22:45:59 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'kolabformat' not found in /var/www/htdocs/webmail/plugins/caldav_calendar/libkolab/lib/kolab_storage.php:107
Stack trace:
#0 /var/www/htdocs/webmail/plugins/caldav_calendar/libkolab/lib/kolab_storage.php(181): kolab_storage::setup()
#1 /var/www/htdocs/webmail/plugins/caldav_calendar/calendar/drivers/kolab/kolab_driver.php(90): kolab_storage::get_folders('event')
#2 /var/www/htdocs/webmail/plugins/caldav_calendar/calendar/drivers/kolab/kolab_driver.php(1593): kolab_driver->_read_calendars()
#3 /var/www/htdocs/webmail/plugins/caldav_calendar/calendar/calendar.php(1734): kolab_driver->pending_alarms(1588279800)
#4 /var/www/htdocs/webmail/program/lib/Roundcube/rcube_plugin_api.php(457): calendar->pending_alarms(Array)
#5 /var/www/htdocs/webmail/plugins/caldav_calendar/libcalendaring/libcalendaring.php(697): rcube_plugin_api->exec_hook('pending_alarms', Array)
#6 /var/www/htdocs/we in /var/www/htdocs/webmail/plugins/caldav_calendar/libkolab/lib/kolab_storage.php on line 107
```

**Comment by texxasrulez** [comment]
From what I see in your errors logs, your issue is as follows:

You have the plugins installed under /roundcube_root/plugins/caldav_calendar/calendar/.
The directory structure should be /roundcube_root/plugins/calendar/, /roundcube_root/plugins/libcalendaring/, /roundcube_root/plugins/libkolab/
Move calendar, libcalendaring and libkolab directories one level down and this should fix your issue ..

**Comment by Yannik** [comment]
@texxasrulez You're right, I have cloned into plugins/caldav_calendar.

However, I've also symlinked the individual folders like this:
```
ln -s caldav_calendar/calendar/ .
ln -s caldav_calendar/libkolab/ .
ln -s caldav_calendar/libcalendaring/ .
```

**Comment by Yannik** [comment]
Couldn't reproduce this today, therefore closing this until this occurs again.
