### ISSUE TITLE
Call to a member function format() on null in /data/www/webmail/plugins/calendar/calendar.php

### ISSUE THREAD

**Issue by zraly** [texxasrulez/caldav_calendar#9]
Hi, 

we are getting this error, it seems, that variable `$event` does not have any key `start`, which is required on the line 3167. 

Last version. PHP 7.2.

```
[24-Feb-2020 11:15:08 UTC] PHP Fatal error:  Uncaught Error: Call to a member function format() on null in /data/www/webmail/plugins/calendar/calendar.php:3167
Stack trace:
#0 /data/www/webmail/program/lib/Roundcube/rcube_plugin_api.php(441): calendar->mail_messagebody_html(Array)
#1 /data/www/webmail/program/include/rcmail_output_html.php(1470): rcube_plugin_api->exec_hook(‘template_object...‘, Array)
#2 [internal function]: rcmail_output_html->xml_command(Array)
#3 /data/www/webmail/program/include/rcmail_output_html.php(1204): preg_replace_callback(‘/<roundcube:([-...‘, Array, ‘<roundcube:obje...‘)
#4 /data/www/webmail/program/include/rcmail_output_html.php(776): rcmail_output_html->parse_xml(‘<roundcube:obje...’)
#5 /data/www/webmail/program/include/rcmail_output_html.php(610): rcmail_output_html->parse(‘message’, false)
#6 /data/www/webmail/program/steps/mail/show.inc(171): rcmail_output_html->send(‘message’, false)
#7 /data/www/we in /data/www/webmail/plugins/calendar/calendar.php on line 3167
[24-Feb-2020 11:16:17 UTC] PHP Fatal error:  Uncaught Error: Call to a member function format() on null in /data/www/webmail/plugins/calendar/calendar.php:3167
```

**Comment by texxasrulez** [comment]
What are you trying to do? I need detailed information on what you are trying to achieve, what you did to achieve it and so forth ....

**Comment by zraly** [comment]
I have this plugin installed in Roundcube and I am trying to open an email with .ics file included. Then, it throws error 500 and above stack trace is logged. I tried more different e-mails with .ics files.

**Comment by texxasrulez** [comment]
I cannot recreate this issue. I can open all emails with .ics attachment without issue ... 
What is the last commit you are running? I update this thing pretty regularly so you may have an old version. This plugin is definitely a WIP and regular updates happen.

**Comment by texxasrulez** [comment]
Closing due to no input
